# NumPy slicing
This notebook contains a few examples of how to extract specific rows and columns from a NumPy array. This concept is called slicing, and it is often needed when you work with a dataset that is represented as a two-dimensional NumPy array.

In [2]:
# Create a two-dimensional array with 3 rows and 4 columns
import numpy as np
data = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
data

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [3]:
# display all rows and the first column
data[:,0]

array([1, 5, 9])

In [4]:
# Display the first two row and all columns
data[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
# display all columns and the last row
data[-1:,:]

array([[ 9, 10, 11, 12]])

In [6]:
# display all rows and all columns after the first
data[:,1:]

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [7]:
# display all rows and the last two columns
data[:,-2:]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [8]:
# display the first two rows, and the second and third column
data[:2,1:3]

array([[2, 3],
       [6, 7]])

In [9]:
# all rows and the first column
labels = data[:,0]

In [10]:
# all rows and all columns except the first
features = data[:,1:]